[package]
name = "deamon"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"     # Optional, für die Speicherung als JSON (z.B. loggen)
active-win-pos-rs = "0.8"
